---
title: Code
---

The following list provides links to the slides and code used in the guided coding sessions. The solutions to the challenges will be made available through RStudio Server.

<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="day1" class="panel-title">
<a data-toggle="collapse" href="#collapse1">Monday October 15: Introduction to social media research.</a>
</h2>
</div>
<div id="collapse1" class="panel-collapse collapse in" style="margin:12px">

<ul>
<li><p><a href="slides/01-slides-intro.pdf">SLIDES: Introduction to social media research.</a></p>
</li>

<li><p><a href="code/00-setup.html">Introduction to RMarkdown and Setup</a> (<a href="code/00-setup.Rmd">.Rmd file</a>)</p>
</li>

</ul>
</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="day2" class="panel-title">
<a data-toggle="collapse" href="#collapse2">Tuesday October 16: Text analysis using R.</a>
</h2>
</div>
<div id="collapse2" class="panel-collapse collapse in" style="margin:12px">

<ul>
<li><p><a href="slides/02-intro-text-analysis.pdf">SLIDES: Introduction to automated text analysis.</a></p>
</li>

<li><p><a href="code/01-loops-functions.html">R refresher. Loops and functions.</a> (<a href="code/01-loops-functions.Rmd">.Rmd file</a>)</p>
</li>


<li><p><a href="code/02-intro-text-analysis.html">Basics of text analysis.</a> (<a href="code/02-intro-text-analysis.Rmd">.Rmd file</a>)</p>
</li>

<li><p><a href="code/03-quanteda-intro.html">Automated text analysis with quanteda.</a> (<a href="code/03-quanteda-intro.Rmd">.Rmd file</a>)</p>
</li>

<li><p><a href="code/challenge1.Rmd">Coding challenge 1 (.Rmd file)</a></p>
</li>

<li><p><a href="slides/03-dictionary-methods.pdf">SLIDES: Dictionary methods.</a></p>
</li>

<li><p><a href="code/04-dictionary-methods.html">Dictionary methods.</a> (<a href="code/04-dictionary-methods.Rmd">.Rmd file</a>)</p>
</li>

<li><p><a href="code/challenge2.Rmd">Coding challenge 2 (.Rmd file)</a></p>
</li>


</ul>
</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="day3" class="panel-title">
<a data-toggle="collapse" href="#collapse3">Wednesday October 17: Supervised and unsupervised modeling of text.</a>
</h2>
</div>
<div id="collapse3" class="panel-collapse collapse in" style="margin:12px">

<ul>
<li><p><a href="slides/04-supervised-learning.pdf">SLIDES: Supervised machine learning.</a></p>
</li>

<li><p><a href="code/05-supervised-learning.html">Supervised machine learning.</a> (<a href="code/05-supervised-learning.Rmd">.Rmd file</a>)</p>
</li>


<li><p><a href="code/06-advanced-supervised-learning.html">Advanced examples of supervised machine learning.</a> (<a href="code/06-advanced-supervised-learning.Rmd">.Rmd file</a>)</p>
</li>

<li><p><a href="code/challenge3.Rmd">Coding challenge 3 (.Rmd file)</a></p>
</li>

<li><p><a href="slides/05-topic-models.pdf">SLIDES: Topic models.</a></p>
</li>

<li><p><a href="code/07-text-discovery.html">Discovery in large-scale text.</a> (<a href="code/07-text-discovery.Rmd">.Rmd file</a>)</p>
</li>

<li><p><a href="code/08-topic-models.html">Topic models.</a> (<a href="code/08-topic-models.Rmd">.Rmd file</a>)</p>
</li>

<li><p><a href="code/09-advanced-topic-models.html">Advanced examples of topic models.</a> (<a href="code/09-advanced-topic-models.Rmd">.Rmd file</a>)</p>
</li>

<li><p><a href="code/challenge4.Rmd">Coding challenge 4 (.Rmd file)</a></p>
</li>


</ul>
</div>
</div>
</div>



<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="day3" class="panel-title">
<a data-toggle="collapse" href="#collapse3">Thursday October 18: Collecting and analyzing Twitter data.</a>
</h2>
</div>
<div id="collapse3" class="panel-collapse collapse in" style="margin:12px">

<ul>
<li><p><a href="slides/06-twitter-data.pdf">SLIDES: Twitter data.</a></p>
</li>

<li><p><a href="code/10-twitter-streaming-data-collection.html">Collecting data from Twitter's Streaming API.</a> (<a href="code/10-twitter-streaming-data-collection.Rmd">.Rmd file</a>)</p>
</li>


<li><p><a href="code/challenge5.Rmd">Coding challenge 5 (.Rmd file)</a></p>
</li>

<li><p><a href="code/11-twitter-REST-data-collection.html">Collecting data from Twitter's REST API.</a> (<a href="code/11-twitter-REST-data-collection.Rmd">.Rmd file</a>)</p>
</li>

<li><p><a href="code/challenge6.Rmd">Coding challenge 6 (.Rmd file)</a></p>
</li>


</ul>
</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="day3" class="panel-title">
<a data-toggle="collapse" href="#collapse3">Friday October 19: Advanced topics.</a>
</h2>
</div>
<div id="collapse3" class="panel-collapse collapse in" style="margin:12px">

<ul>
<li><p><a href="slides/07-APIs.pdf">SLIDES: APIs.</a></p>
</li>

<li><p><a href="code/12-apis.html">Working with the NYTimes API.</a> (<a href="code/12-apis.Rmd">.Rmd file</a>)</p>
</li>

<li><p><a href="code/challenge7.Rmd">Coding challenge 7 (.Rmd file)</a></p>
</li>

<li><p><a href="slides/08-embeddings.pdf">SLIDES: Word embeddings.</a></p>
</li>

<li><p><a href="code/13-word-embeddings.html">Word embeddings.</a> (<a href="code/13-word-embeddings.Rmd">.Rmd file</a>)</p>
</li>


</ul>
</div>
</div>
</div>