---
output:
  html_document:
    toc: true
    toc_depth: 3
---

<div class="container">
<div class="jumbotron" style="margin-left:-15px">
<h1 class="title">Quantitative Text Analysis</h1>
<h2 class="subtitle">with Applications to Social Media Research</h1>
<p>University of Vienna, October 15-19 2018</p>
</div>
</div>

Citizens across the globe spend an increasing proportion of their daily lives on social media websites, such as Twitter and Facebook. Their activities leave behind granular, time-stamped footprints of human behavior and personal interactions that represent a new and exciting source of data to study standing questions about political and social behavior. At the same time, the volume and heterogeneity of social media data present unprecedented methodological challenges. The goal of this short course is to gain the skills necessary to automate the process of downloading, cleaning, and analyzing textual data from social media sites using the R programming language.

# Instructor

<table class = "table table-striped">
<tr>
<td><a href="http://www.pablobarbera.com"><strong>Pablo Barberá</strong></a> (Instructor)</td>
<td><a href="mailto:P.Barbera@lse.ac.uk">P.Barbera@lse.ac.uk</a></td>
<td><a href="https://www.twitter.com/p_barbera">@p_barbera</a></td>
</tr>
</table>


# Schedule

<table class = "table table-striped table-hover">
<tr>
<td>Monday October 15, 2018</td>
<td><b>Session 1</b></td>
<td>Social media research.</td>
<td> 14:00&ndash;16:30 </td>
</tr>

<td>Tuesday October 16, 2018</td>
<td><b>Session 1</b></td>
<td>R refresher. Text analysis.</td>
<td> 09:00&ndash;12:00 </td>
</tr>

<tr>
<td></td>
<td><b>Session 2</b></td>
<td>Dictionary methods.</td>
<td> 13:00&ndash;15:00 </td>
</tr>


<td>Wednesday October 17, 2018</td>
<td><b>Session 1</b></td>
<td>Supervised text classification.</td>
<td> 9:00&ndash;12:00 </td>
</tr>

<tr>
<td></td>
<td><b>Session 2</b></td>
<td>Topic models</td>
<td> 14:00&ndash;17:30 </td>
</tr>

<td>Thursday October 18, 2018</td>
<td><b>Session 1</b></td>
<td>Collecting Twitter data</td>
<td> 09:00&ndash;12:00 </td>
</tr>

<tr>
<td></td>
<td><b>Session 2</b></td>
<td>Analyzing Twitter data.</td>
<td> 16:00&ndash;19:00 </td>
</tr>

<td>Friday October 19, 2018</td>
<td><b>Session 1</b></td>
<td>Advanced topics</td>
<td> 11:00&ndash;13:00 </td>
</tr>

</table>


# Prerequisites

The course assumes intermediate familiarity with the R statistical programming language. Participants should be able to know how to read datasets in R, work with vectors and data frames, and run basic statistical analyses, such as linear regression. More advanced knowledge of statistical computing, such as writing functions and loops, is helpful but not required.

Students are expected to bring a laptop to class and follow along the coding section of each session.

# Software 

This course will use [R](https://www.r-project.org/), which is a free and open-source programming language primarily used for statistics and data analysis. We will also use [RStudio](https://www.rstudio.com/), which is an easy-to-use interface to R. 

Installing R or RStudio prior to the workshop is not necessary. The instructor will provide individual login details to an RStudio Server that all workshop participants can access to run their code.

# License and credit

Science should be open, and this course builds up other open licensed material, so unless otherwise noted, all materials for this class are licensed under a <a rel="license" href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

The layout for this website was designed by [Jeffrey Arnold](http://www.jrnold.me/) (thanks!).

The source for the materials of this course is on GitHub at <a href="https://github.com/pablobarbera/text-analysis-vienna">pablobarbera/text-analysis-vienna</a>

# Feedback

If you have any feedback on the course or find any typos or errors in this website go to [issues](https://github.com/pablobarbera/ECPR-SC105/issues), click on the "New Issue" button to create a new issue, and add your suggestion or describe the problem.


